# Generated by Django 4.2 on 2024-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_tagpost_alter_women_cat_women_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='women', to='women.tagpost'),
        ),
    ]
