# Generated by Django 5.0.7 on 2024-10-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0007_husband_women_husband"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="women",
            options={
                "ordering": ["-time_create"],
                "verbose_name": "Известные женщины",
                "verbose_name_plural": "Известные женщины",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="women.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="husband",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="woman",
                to="women.husband",
                verbose_name="Муж",
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="is_published",
            field=models.BooleanField(
                choices=[(False, "Черновик"), (True, "Опубликовано")],
                default=0,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="women",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="SLUG"),
        ),
        migrations.AlterField(
            model_name="women",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="women",
                to="women.tagpost",
                verbose_name="Теги",
            ),
        ),
    ]
